
// Example Menubar with Event generated by menu item

import java.applet.*;
import java.awt.*;
import java.awt.event.*;
/* <applet code = "MenuDemo" width = 300 height=300>
   	<param name = width value = 100>
   	<param name = height value =100>
   </applet>	*/

public class MenuDemo extends Applet implements ActionListener
{
	Frame f;
	TextArea text1;
	MenuItem mi1;

	public void init()
	{
		int width = Integer.parseInt(getParameter("width"));
		int height = Integer.parseInt(getParameter("height"));

		f = new Frame("DemoFrame");
		f.setSize(width,height);
		text1 = new TextArea(" " , 80,40);
		f.add(text1);
		MenuBar mb = new MenuBar();
		f.setMenuBar(mb);	// Setting MenuBar on Frame

		Menu file = new Menu("file");
		mi1= new MenuItem("file");
		file.add(mi1); 	// Or use this line of code  ... file.add(new MenuItem("file"));
		mi1.addActionListener(this);
		file.add(new MenuItem("new.."));
		file.add(new MenuItem("open"));
		file.add(new MenuItem("close"));
		file.add(new MenuItem("-"));
		file.add(new MenuItem("quit"));
		mb.add(file);

		Menu edit = new Menu("edit");
		edit.add(new MenuItem("cut"));
		edit.add(new MenuItem("copy"));
		edit.add(new MenuItem("paste"));
		edit.add(new MenuItem("-"));
		//mb.add(edit);

		Menu sub = new Menu("Special");
		sub.add(new MenuItem("ft"));
		sub.add(new MenuItem("st"));
		sub.add(new MenuItem("td"));
		edit.add(sub);
		edit.add(new CheckboxMenuItem("debug",true));
		edit.add(new CheckboxMenuItem("testing",true));
		mb.add(edit);
		f.show();

	}

	public void actionPerformed(ActionEvent ae)
	{
		if(ae.getSource()==mi1)
		{
			text1.append("File Menu Option Clicked");
		}
	}
}