spring.datasource.url=jdbc:postgresql://localhost:5432/erp_college
spring.datasource.username=erp_user
spring.datasource.password=sappu0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081

# File upload config for Excel import
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.upload.dir=uploads/profiles
